name = "leadring"
main = "server.ts"
compatibility_date = "2024-01-01"

[vars]
# Add your environment variables here for production
# GOOGLE_CLIENT_ID = "..."
# GOOGLE_CLIENT_SECRET = "..."
# APP_URL = "https://leadring.pages.dev"

[[kv_namespaces]]
# For storing sessions if you want to move away from cookies
# binding = "SESSIONS"
# id = "..."

[site]
bucket = "./dist"
